image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build_container
  - test
  # - release
  # - deploy

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  # MOUNT_POINT: /builds/$CI_PROJECT_PATH/jackal_ws
  GIT_SUBMODULE_STRATEGY: recursive

build_container:
  stage: build_container
  only:
    changes:
      - docker/Dockerfile
      - nn_closed_loop/setup.py
      - nn_partition/setup.py
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CONTAINER_TEST_IMAGE -f docker/Dockerfile .
    - docker push $CONTAINER_TEST_IMAGE

test_partition:
  stage: test
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run -v /builds/mit-acl/ford_ugvs/nn_robustness_analysis:/home/nn_robustness_analysis $CONTAINER_TEST_IMAGE python -m nn_partition.tests.test
    # - python -m nn_partition.tests.test

# test_closed_loop:
#   image: $CONTAINER_TEST_IMAGE
#   script:
#     - python -m nn_closed_loop.tests.test

# release-image:
#   stage: release
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#     - docker push $CONTAINER_RELEASE_IMAGE
#   only:
#     changes:
#       - docker/Dockerfile
#       - nn_closed_loop/setup.py
#       - nn_partition/setup.py
#     refs:
#       - merge_requests
#   # only:
#   #   - master

# deploy:
#   stage: deploy
#   script:
#     - ./deploy.sh
#   only:
#     - master
